#!/usr/bin/env bash
#
# ralph.sh - Ralph Wiggum Loop for Jido Workspace
#
# A deterministic outer loop that runs Claude Code in a while loop.
# The agent handles the creative work; this script handles the boring stuff:
# - Ensuring we're on a feature branch (not main)
# - Validating prompt.md exists
# - Running the agent in a loop
# - Logging iterations
#
# Usage:
#   ./ralph.sh [prompt_file] [--max-iterations N] [--cooldown SECONDS]
#
# Examples:
#   ./ralph.sh ralph/PROMPT.md
#   ./ralph.sh ralph/PROMPT.md --max-iterations 50
#   ./ralph.sh  # Uses ralph/PROMPT.md by default
#

set -euo pipefail

# Configuration
DEFAULT_PROMPT="ralph/PROMPT.md"
DEFAULT_MAX_ITERATIONS=100
DEFAULT_COOLDOWN=5
LOG_DIR="ralph/logs"
AGENT_CMD="claude"  # Claude Code CLI

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
PROMPT_FILE="${1:-$DEFAULT_PROMPT}"
MAX_ITERATIONS=$DEFAULT_MAX_ITERATIONS
COOLDOWN=$DEFAULT_COOLDOWN

shift || true
while [[ $# -gt 0 ]]; do
    case $1 in
        --max-iterations)
            MAX_ITERATIONS="$2"
            shift 2
            ;;
        --cooldown)
            COOLDOWN="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: ./ralph.sh [prompt_file] [--max-iterations N] [--cooldown SECONDS]"
            echo ""
            echo "Options:"
            echo "  prompt_file          Path to prompt file (default: ralph/PROMPT.md)"
            echo "  --max-iterations N   Maximum loop iterations (default: 100)"
            echo "  --cooldown SECONDS   Seconds between iterations (default: 5)"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Logging
log() {
    local level="$1"
    local message="$2"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "${timestamp} [${level}] ${message}"
    echo "${timestamp} [${level}] ${message}" >> "${LOG_FILE}"
}

info() { log "${BLUE}INFO${NC}" "$1"; }
warn() { log "${YELLOW}WARN${NC}" "$1"; }
error() { log "${RED}ERROR${NC}" "$1"; }
success() { log "${GREEN}OK${NC}" "$1"; }

# Pre-flight checks
preflight_checks() {
    info "Running pre-flight checks..."
    
    # 1. Check we're in a git repo
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        error "Not in a git repository"
        exit 1
    fi
    
    # 2. Check current branch is not main/master
    CURRENT_BRANCH=$(git branch --show-current)
    if [[ "$CURRENT_BRANCH" == "main" || "$CURRENT_BRANCH" == "master" ]]; then
        error "Cannot run on main/master branch. Create a feature branch first:"
        echo -e "  ${YELLOW}git checkout -b ralph/your-feature-name${NC}"
        exit 1
    fi
    success "On branch: $CURRENT_BRANCH"
    
    # 3. Check prompt file exists
    if [[ ! -f "$PROMPT_FILE" ]]; then
        error "Prompt file not found: $PROMPT_FILE"
        echo -e "Create it with your task description. Example:"
        echo -e "  ${YELLOW}echo 'Your task here...' > $PROMPT_FILE${NC}"
        exit 1
    fi
    success "Prompt file: $PROMPT_FILE"
    
    # 4. Check FIX_PLAN.md exists (create if not)
    FIX_PLAN_FILE="$(dirname "$PROMPT_FILE")/FIX_PLAN.md"
    if [[ ! -f "$FIX_PLAN_FILE" ]]; then
        warn "FIX_PLAN.md not found, creating..."
        cat > "$FIX_PLAN_FILE" << 'EOF'
# Fix Plan

## Current Status
- **Started**: $(date '+%Y-%m-%d %H:%M')
- **Status**: In Progress

## Known Issues & Blockers

_No issues yet. The agent will update this file as it discovers problems._

## Completed Tasks

_Tasks will be logged here as they are completed._

---
*Auto-generated by ralph.sh*
EOF
        success "Created: $FIX_PLAN_FILE"
    else
        success "Fix plan: $FIX_PLAN_FILE"
    fi
    
    # 5. Check claude CLI is available
    if ! command -v "$AGENT_CMD" &> /dev/null; then
        error "Claude Code CLI not found. Install it first:"
        echo -e "  ${YELLOW}npm install -g @anthropic-ai/claude-code${NC}"
        exit 1
    fi
    success "Agent CLI: $AGENT_CMD"
    
    # 6. Check for uncommitted changes (warn only)
    if [[ -n $(git status --porcelain) ]]; then
        warn "You have uncommitted changes. The agent may commit them."
    fi
    
    info "Pre-flight checks passed ✓"
}

# Build the prompt for claude
build_prompt() {
    local prompt_content
    prompt_content=$(cat "$PROMPT_FILE")
    
    # The prompt instructs Claude to read the files, not embed them
    cat << EOF
Read and follow the instructions in @${PROMPT_FILE}

Also read:
- @$(dirname "$PROMPT_FILE")/FIX_PLAN.md for current status and blockers
- @$(dirname "$PROMPT_FILE")/AGENT.md for project-specific context (if it exists)
- @AGENTS.md for workspace conventions

Current iteration: ${ITERATION}/${MAX_ITERATIONS}
Branch: ${CURRENT_BRANCH}

When you finish this iteration:
1. Update FIX_PLAN.md with your progress
2. Commit your changes with a descriptive message
3. Push to the remote branch

If you've completed the task fully, create a file called 'ralph/DONE' to signal completion.
EOF
}

# Run a single iteration
run_iteration() {
    local iteration=$1
    local iteration_log="${LOG_DIR}/iteration_${iteration}.log"
    
    info "Starting iteration ${iteration}/${MAX_ITERATIONS}"
    
    # Build prompt
    local prompt
    prompt=$(build_prompt)
    
    # Run claude with the prompt
    # Stream output to both terminal and log file
    echo "$prompt" | $AGENT_CMD 2>&1 | tee -a "$iteration_log"
    
    local exit_code=${PIPESTATUS[1]}
    
    if [[ $exit_code -ne 0 ]]; then
        warn "Iteration ${iteration} exited with code ${exit_code}"
    else
        success "Iteration ${iteration} completed"
    fi
    
    return $exit_code
}

# Check if we should stop
should_stop() {
    # Check for DONE signal file
    if [[ -f "ralph/DONE" ]]; then
        info "Found ralph/DONE - task completed!"
        return 0
    fi
    
    # Check if FIX_PLAN.md indicates completion
    if grep -q "Status.*COMPLETED\|ALL.*RESOLVED\|DONE" "$(dirname "$PROMPT_FILE")/FIX_PLAN.md" 2>/dev/null; then
        info "FIX_PLAN.md indicates completion"
        return 0
    fi
    
    return 1
}

# Main loop
main() {
    # Create log directory first
    mkdir -p "$LOG_DIR"
    
    # Set up logging
    SESSION_ID=$(date '+%Y%m%d_%H%M%S')
    LOG_FILE="${LOG_DIR}/ralph_${SESSION_ID}.log"
    
    echo -e "${GREEN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                    RALPH WIGGUM LOOP                         ║"
    echo "║          'Me fail English? That's unpossible!'               ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    
    info "Session: ${SESSION_ID}"
    info "Log file: ${LOG_FILE}"
    
    # Run pre-flight checks
    preflight_checks
    
    echo ""
    info "Starting loop with:"
    info "  Prompt: $PROMPT_FILE"
    info "  Max iterations: $MAX_ITERATIONS"
    info "  Cooldown: ${COOLDOWN}s"
    echo ""
    
    # Confirm start
    read -p "Press Enter to start the loop (Ctrl+C to cancel)..."
    
    ITERATION=0
    START_TIME=$(date +%s)
    
    while [[ $ITERATION -lt $MAX_ITERATIONS ]]; do
        ITERATION=$((ITERATION + 1))
        
        echo ""
        echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        
        # Run iteration
        if ! run_iteration $ITERATION; then
            warn "Iteration failed, continuing..."
        fi
        
        # Check for completion
        if should_stop; then
            success "Task completed!"
            break
        fi
        
        # Cooldown between iterations
        if [[ $ITERATION -lt $MAX_ITERATIONS ]]; then
            info "Cooling down for ${COOLDOWN}s..."
            sleep $COOLDOWN
        fi
    done
    
    # Summary
    END_TIME=$(date +%s)
    DURATION=$((END_TIME - START_TIME))
    DURATION_MIN=$((DURATION / 60))
    
    echo ""
    echo -e "${GREEN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                      SESSION COMPLETE                        ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    info "Iterations: $ITERATION"
    info "Duration: ${DURATION_MIN} minutes (${DURATION}s)"
    info "Log: ${LOG_FILE}"
    
    # Show final git status
    echo ""
    info "Git status:"
    git log --oneline -5
}

# Handle Ctrl+C gracefully
trap 'echo ""; warn "Interrupted by user"; exit 130' INT

# Run
main
