defmodule Karo.Repo.Migrations.InitKaroSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scheduled_actions, primary_key: false) do
      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "scheduled_actions_conversation_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :payload, :map, null: false, default: %{}
      add :run_at, :utc_datetime_usec, null: false
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:messages, primary_key: false) do
      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "messages_conversation_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :discord_user_id, :text
      add :content, :text, null: false
      add :role, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:conversations, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_activity_at, :utc_datetime_usec
      add :status, :text, null: false
      add :title, :text
      add :discord_thread_id, :text
      add :discord_channel_id, :text, null: false
      add :discord_guild_id, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(
             :conversations,
             [:discord_guild_id, :discord_channel_id, :discord_thread_id],
             name: "conversations_discord_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :conversations,
                     [:discord_guild_id, :discord_channel_id, :discord_thread_id],
                     name: "conversations_discord_key_index"
                   )

    drop table(:conversations)

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop table(:messages)

    drop constraint(:scheduled_actions, "scheduled_actions_conversation_id_fkey")

    drop table(:scheduled_actions)
  end
end