defmodule Mix.Tasks.Roadmap.Pr do
  @moduledoc """
  Create a PR for a roadmap item using the `gh` CLI.

  ## Usage

      mix roadmap.pr 001-jido-core/001-hand-review
      mix roadmap.pr <item-id> --draft

  Requires the item to be in `implementing` state.
  Uses `gh pr create` to open a pull request.
  Transitions state to `in_pr`.
  """

  use Mix.Task
  require Logger

  alias JidoWorkspace.Roadmap

  @shortdoc "Create a PR for a roadmap item"

  @switches [draft: :boolean]

  def run(args) do
    {opts, [item_id | _]} = OptionParser.parse!(args, switches: @switches)

    case Roadmap.load_item(item_id) do
      {:ok, item} ->
        if item["state"] != "implementing" do
          Mix.raise("Item must be in 'implementing' state to create PR. Current: #{item["state"]}")
        end

        run_pr(item, opts)

      {:error, _} ->
        Mix.raise("Item not found: #{item_id}")
    end
  end

  defp run_pr(item, opts) do
    item_dir = Path.join(Roadmap.base_path(), item["id"])
    plan_path = Path.join(item_dir, "plan.md")

    Logger.info("Creating PR for: #{item["title"]}")

    body = build_pr_body(item, plan_path)

    gh_args = [
      "pr",
      "create",
      "--title",
      "[Roadmap] #{item["title"]}",
      "--body",
      body,
      "--base",
      "main"
    ]

    gh_args = if opts[:draft], do: gh_args ++ ["--draft"], else: gh_args

    Logger.info("Running: gh #{Enum.join(gh_args, " ")}")

    case System.cmd("gh", gh_args, stderr_to_stdout: true) do
      {output, 0} ->
        pr_url = String.trim(output)
        Logger.info("Created PR: #{pr_url}")

        {:ok, updated} =
          item
          |> Map.put("pr_url", pr_url)
          |> Roadmap.transition_item("in_pr")

        Roadmap.save_item(updated)

        Logger.info("Item transitioned to 'in_pr'")
        Mix.shell().info("\nPR: #{pr_url}")
        Mix.shell().info("After merge: mix roadmap.complete #{item["id"]}")

      {output, code} ->
        Mix.raise("Failed to create PR (exit #{code}): #{output}")
    end
  end

  defp build_pr_body(item, plan_path) do
    plan_content =
      if File.exists?(plan_path) do
        File.read!(plan_path) |> String.slice(0, 2000)
      else
        ""
      end

    """
    ## Roadmap Item

    **ID:** `#{item["id"]}`
    **Section:** #{Enum.join(item["section"] || [], " > ")}

    ## Overview

    #{item["overview"] || item["title"]}

    ## Plan

    #{plan_content}

    ---
    _Generated by `mix roadmap.pr`_
    """
  end
end
