defmodule JidoHub.Repo.Migrations.MigrateToLatest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pods) do
      add :visibility, :text, null: false, default: "private"
    end
  end

  def down do
    alter table(:pods) do
      remove :visibility
    end
  end
end
