defmodule JidoHub.Repo.Migrations.AddLogsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :is_suspended, :boolean, null: false, default: false
      add :is_deleted, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :user_type, :text, null: false, default: "user"
      add :metadata, :map, null: false, default: %{}

      add :user_id,
          references(:users,
            column: :id,
            name: "logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :target_user_id,
          references(:users,
            column: :id,
            name: "logs_target_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :org_id,
          references(:organizations,
            column: :id,
            name: "logs_org_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:logs, [:action])
    create index(:logs, [:user_type])
    create index(:logs, [:user_id])
    create index(:logs, [:target_user_id])
    create index(:logs, [:org_id])
    create index(:logs, [:inserted_at])
  end

  def down do
    drop constraint(:logs, "logs_user_id_fkey")

    drop constraint(:logs, "logs_target_user_id_fkey")

    drop constraint(:logs, "logs_org_id_fkey")

    drop table(:logs)

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :is_deleted
      remove :is_suspended
    end
  end
end
