defmodule JidoHub.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :username, :text, null: false
      add :hashed_password, :text
      add :confirmed_at, :utc_datetime_usec
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:username], name: "users_unique_username_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:pods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :settings, :map, default: %{}
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:pods, [:owner_type, :owner_id, :slug],
             name: "pods_unique_slug_per_owner_index"
           )

    create table(:pod_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"
      add :joined_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pod_id,
          references(:pods,
            column: :id,
            name: "pod_memberships_pod_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "pod_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:pod_memberships, [:pod_id, :user_id],
             name: "pod_memberships_unique_membership_index"
           )

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :settings, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "organizations_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"
      add :joined_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:memberships, [:user_id, :organization_id],
             name: "memberships_unique_user_organization_index"
           )

    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :role, :text, null: false, default: "member"
      add :token, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :accepted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "invitations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :invited_by_id,
          references(:users,
            column: :id,
            name: "invitations_invited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:invitations, [:token], name: "invitations_unique_token_index")

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
  end

  def down do
    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop table(:api_keys)

    drop_if_exists unique_index(:invitations, [:token], name: "invitations_unique_token_index")

    drop constraint(:invitations, "invitations_organization_id_fkey")

    drop constraint(:invitations, "invitations_invited_by_id_fkey")

    drop table(:invitations)

    drop_if_exists unique_index(:memberships, [:user_id, :organization_id],
                     name: "memberships_unique_user_organization_index"
                   )

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop constraint(:memberships, "memberships_organization_id_fkey")

    drop table(:memberships)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop constraint(:organizations, "organizations_owner_id_fkey")

    drop table(:organizations)

    drop_if_exists unique_index(:pod_memberships, [:pod_id, :user_id],
                     name: "pod_memberships_unique_membership_index"
                   )

    drop constraint(:pod_memberships, "pod_memberships_pod_id_fkey")

    drop constraint(:pod_memberships, "pod_memberships_user_id_fkey")

    drop table(:pod_memberships)

    drop_if_exists unique_index(:pods, [:owner_type, :owner_id, :slug],
                     name: "pods_unique_slug_per_owner_index"
                   )

    drop table(:pods)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
