name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to Hex
    uses: agentjido/github-actions/.github/workflows/elixir-publish.yml@main
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
